<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net9.0;net9.0-android;net9.0-ios18.0</TargetFrameworks>
    <OutputType>Library</OutputType>
    <UseMaui>true</UseMaui>
    <MauiVersion Condition="$(TargetFramework.Contains('net9.0'))">9.0.0</MauiVersion>
    <SingleProject>true</SingleProject>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Nullable>enable</Nullable>
    <IsPackable>true</IsPackable>

    <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios' and $(TargetFramework.Contains('net9.0'))">12.2</SupportedOSPlatformVersion>
    <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">24.0</SupportedOSPlatformVersion>

    <AppendTargetFrameworkToOutputPath>true</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>true</AppendRuntimeIdentifierToOutputPath>

    <Configurations>Debug;Release</Configurations>
    <Platforms>AnyCPU;Simulator;Device</Platforms>
  </PropertyGroup>

  <!--NuGet package-->
  <PropertyGroup>
    <Product>Superdev.Maui</Product>
    <Description>Support library for .NET MAUI apps</Description>
    <Version>1.0.0</Version>
    <Authors>superdev;Thomas Galliker</Authors>
    <PackageId>Superdev.Maui</PackageId>
    <PackageTags>maui;support;library;controls;effects;behaviors;tools;extensions;custom;building;blocks</PackageTags>
    <PackageIcon>logo.png</PackageIcon>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageProjectUrl>https://github.com/superdevgmbh/Superdev.Maui</PackageProjectUrl>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/superdevgmbh/Superdev.Maui</RepositoryUrl>
    <Company>superdev GmbH</Company>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <Copyright>Copyright $([System.DateTime]::Now.ToString(`yyyy`)) © Thomas Galliker</Copyright>
    <!--<PackageReleaseNotes>$([System.IO.File]::ReadAllText("$(MSBuildProjectDirectory)/../ReleaseNotes.txt"))</PackageReleaseNotes>-->
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <EmbedAllSources>true</EmbedAllSources>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\README.md" Pack="True" PackagePath="\" />
    <None Include="..\LICENSE" Pack="True" PackagePath="\" />
    <None Include="..\logo.png" Pack="True" PackagePath="\" />
  </ItemGroup>
  
  <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <!-- Android build properties -->
  <PropertyGroup Condition="$(TargetFramework.Contains('-android'))">
    <AndroidEnableMultiDex>true</AndroidEnableMultiDex>
    <AndroidDexTool>d8</AndroidDexTool>
  </PropertyGroup>
  <PropertyGroup Condition="$(TargetFramework.Contains('-android')) and '$(Configuration)' == 'Debug'">
    <AndroidLinkMode>None</AndroidLinkMode>
  </PropertyGroup>
  <PropertyGroup Condition="$(TargetFramework.Contains('-android')) and '$(Configuration)' == 'Release'">
    <AndroidLinkMode>SdkOnly</AndroidLinkMode>
    <AndroidLinkTool>r8</AndroidLinkTool>
  </PropertyGroup>

  <!-- iOS build properties -->
  <PropertyGroup Condition="$(TargetFramework.Contains('-ios')) and '$(Configuration)' == 'Debug'">
    <MtouchDebug>true</MtouchDebug>
    <MtouchLink>None</MtouchLink>
  </PropertyGroup>
  <PropertyGroup Condition="$(TargetFramework.Contains('-ios')) and '$(Configuration)' == 'Release'">
    <MtouchDebug>false</MtouchDebug>
    <MtouchLink>SdkOnly</MtouchLink>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Maui.Controls" Version="$(MauiVersion)"/>
  </ItemGroup>

  <ItemGroup>
    <None Remove="Resources\Images\*.png"/>
    <EmbeddedResource Include="Resources\Images\*.png"/>
  </ItemGroup>

</Project>
